baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'roopkumar das'
theme = 'nostyleplease'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
